### ISSUE TITLE
Build installer(s) using travis

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/natron-plugins#1]
We should add a build script for travis that makes installer(s) on tags.

A direct download should also be used on the Natron website, or better yet create a dedicated section on the Natron website. The github project page for the plugins is "scary" to normal users.

**Comment by blackearth2014** [comment]
I don't have the technical knowhow to do it but let's go for it.

**Comment by rodlie** [comment]
No problem, I will do the work. Just needed to add TODO :)

**Comment by blackearth2014** [comment]
Thanks and cool breeze

**Comment by rodlie** [comment]
Close, as I started work on a plugin manager at https://github.com/rodlie/NatronPluginManager. Still not done, but should be very much usable by the end of this week.
