### ISSUE TITLE
AudioVLC plugin no audio played

### ISSUE THREAD

**Issue by alexxcharr** [NatronGitHub/natron-plugins#10]
Hello,
I am a newbie with natron and  i use it in ubuntu. 
i was trying to add some sound using the AudioVLC plugin but i got no sound.
Opening natron from the terminal and trying it out i got the message 
/bin/sh: 1: exec: vlc: not found

i have vlc installed but i dont know if the plugin is looking in the wrong directory maybe or what the problem might be.

**Comment by rodlie** [comment]
`vlc` must be in your `$PATH`. Did you install a snap/flatpak or a proper package?

**Comment by alexxcharr** [comment]
just now i deleted natron because i installed the snap and reinstalled it with the installer from the webpage and everything works fine. Thank you for the quick response! :)

**Comment by rodlie** [comment]
Good :)

The snap package (of Natron) has several known issues and we can't do anything about it (not maintained by us).
