### ISSUE TITLE
How to write GLSL plugin.

### ISSUE THREAD

**Issue by synxroform** [NatronGitHub/natron-plugins#3]
Can't find any information regarding custom nodes. Many sources in this repository autogenerated and hard to understand. I want to write GLSL node (screen space curvature) that looks like a native Natron node.

**Comment by sozap** [comment]
You should look first at the shadertoy node inside Natron, this is where you'll write your GLSL code.
Once that's done, you can make a group out of it and by saving it you'll get that autogenerated script that will act as a native Natron's node.
For that 2nd part you can look here : https://natron.readthedocs.io/en/rb-2.3/devel/groups.html

**Comment by synxroform** [comment]
Thank you.
