### ISSUE TITLE
vlc_audio looking in the wrong path.

### ISSUE THREAD

**Issue by Elmapul** [NatronGitHub/natron-plugins#4]
the vlc audio plugin is not working on ubuntu 18.04
the natron version that i have installed is the snap version  2.3.14
as for vlc, i tried to install both the deb and the snap version, neither work.

runing natron from the terminal, i got the following error message when i try to run play any file:

/bin/sh: 1: exec: vlc: 

my guess is that the plugin is searching for VLC in the wrong directory, i'm not sure how to solve this for all the distros, but runing the command:
whereis vlc

i got the following result:
vlc: /usr/bin/vlc /usr/lib/x86_64-linux-gnu/vlc /usr/share/vlc /snap/bin/vlc /usr/share/man/man1/vlc.1.gz

so the plugin should either:
do aditional checks to verify if vlc is in those directories before atempt to run it.
run the command whereis vlc, grab the result and use it to launch vlc.

**Comment by rodlie** [comment]
The plugin runs ``exec vlc ...``, should work on any normal setup. Probably related to the use of snap.

**Comment by Elmapul** [comment]
yes, looks like snaps are running in some kind of sandboxing, installing the native version fixed the issue.
i dont know if there is anything that can be done about that.
maybe there is any flag that the snap creator can set to ask for permission to execute external code in natron, but i doubt they will add it just to fix the compatibility of an single add'on, if it were necessary to make natron itself work, they would, but just for an add'on...
not to mention that i dont know if this sandbox can be brokena at all in snap apps...

**Comment by rodlie** [comment]
That's the problem with snaps flatpaks etc. I generally don't recommend using any of them if you want to use Natron.
