### ISSUE TITLE
Writing custom effects

### ISSUE THREAD

**Issue by splidje** [NatronGitHub/natron-plugins#5]
If I start writing a custom Natron effect, is this a good repo to write it in?

**Comment by rodlie** [comment]
If it's a Python plugin, yes.

**Comment by splidje** [comment]
Oh, I didn't notice that! I was thinking of going straight for OFX C++ plugin.

**Comment by devernay** [comment]
1. create a repo that mimics openfx-misc structure like what @baldavenger did: https://github.com/baldavenger/BaldavengerOFX
2. Once it's finished, you can submit it for inclusion in openfx-misc if it's of general use

**Comment by splidje** [comment]
Thank you. I've ended up starting this repo:
https://github.com/splidje/openfx-ajptechnical

Thought I'd mention, in case anyone's intrigued / has any critiques.

**Comment by cgvirus** [comment]
Solved.
